export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const CART_PRODUCT_QUANTITY = 'CART_PRODUCT_QUANTITY'
export const UPDATE_CART = 'UPDATE_CART'
